import assert from "node:assert/strict";
import test from "node:test";
import { createDemoFixture } from "../src/watchtree/fixtures.js";
import { buildWatchTree,orderCandidates,scoreCandidate } from "../src/watchtree/matching.js";

const fixture=createDemoFixture();const eligible=fixture.events.map((e)=>({...e,matching_enabled:true,visibility_state:"matchable_private"}));
test("fixture is versioned, synthetic, and bounded",()=>{assert.equal(fixture.fixture_id,"watchtree-demo-v1");assert.equal(fixture.corpus_version,"demo-corpus-v1");assert.equal(fixture.events.length,48);assert.equal(fixture.candidates.length,3);assert.ok(fixture.events.every((e)=>e.is_synthetic));});
test("deterministic candidate ordering exposes required causal evidence",()=>{const first=orderCandidates(eligible,fixture.candidates);const second=orderCandidates(eligible,fixture.candidates);assert.deepEqual(first,second);assert.deepEqual(first.map((c)=>c.id),[...first].sort((a,b)=>b.score-a.score||b.rare_overlap_count-a.rare_overlap_count||b.shared_path_count-a.shared_path_count||b.exact_overlap_count-a.exact_overlap_count||a.id.localeCompare(b.id)).map((c)=>c.id));for(const c of first){assert.deepEqual(c.evidence_tokens.map((e)=>e.type),["exact","rare","path","difference"]);assert.ok(c.score>=0&&c.score<=1);}});
test("excluded items cannot influence fingerprint or candidates",()=>{const baseline=scoreCandidate(eligible,fixture.candidates[0],fixture.candidates);const excluded=eligible.map((e)=>baseline.evidence_tokens[0]&&e.normalized_content_id===fixture.candidates[0].events[0].normalized_content_id?{...e,sensitivity_excluded:true}:e);const changed=scoreCandidate(excluded,fixture.candidates[0],fixture.candidates);assert.ok(changed.exact_overlap_count<=baseline.exact_overlap_count);assert.equal(buildWatchTree(excluded).eligible_event_count,excluded.filter((e)=>!e.sensitivity_excluded).length);});
test("matching weights sum to one without compatibility percentage",async()=>{const {SCORE_WEIGHTS}=await import("../src/watchtree/constants.js");assert.equal(Object.values(SCORE_WEIGHTS).reduce((a,b)=>a+b,0),1);const source=await import("node:fs").then(({readFileSync})=>readFileSync(new URL("../src/watchtree/WatchTreeExperience.jsx",import.meta.url),"utf8"));assert.doesNotMatch(source,/compatibility|soulmate|% match/i);});
