const en = {
  nav: { story: "Story", privacy: "Privacy", enter: "Enter WatchTree" },
  landing: {
    eyebrow: "Resonance · WatchTree",
    title: "You watched. You remembered. Somewhere, someone followed the same path.",
    body: "Your private viewing trail becomes a living tree. Shared leaves are found without profiles, compatibility percentages, or psychological labels.",
    primary: "Use private demo history",
    secondary: "See how privacy works",
    privacy: "Raw export files stay in your browser. Matching starts off.",
    privacyOverview: {
      eyebrow: "Privacy overview",
      title: "Your viewing path stays yours.",
      body: "WatchTree uses only the viewing material you deliberately choose, with clear boundaries before anything is compared or revealed.",
      points: [
        "You add YouTube URLs or files you explicitly select.",
        "Candidates are synthetic only.",
        "No real user is contacted.",
        "Evidence is revealed only after explicit consent.",
        "You can delete your data whenever you choose.",
        "WatchTree never accesses your YouTube account automatically.",
      ],
    },
    scenes: [
      ["You watched.", "Abstract media moments pass through one synthetic viewer."],
      ["Some moments stayed.", "Retained fragments become a private viewing trail."],
      ["Choose the path.", "Use a synthetic demo or select an extracted HTML/JSON history file."],
      ["A WatchTree grows.", "Repeats, creators, time, and paths become roots, branches, and leaves."],
      ["Another tree appears.", "A server-defined synthetic viewer follows adjacent media paths."],
      ["Shared leaves illuminate.", "Exact overlap, rare signal, shared path, and meaningful difference remain inspectable."],
      ["Enter the product.", "Review exclusions, consent to one evidence path, and trigger a clearly simulated mutual state."],
    ],
  },
  experience: {
    member: "Resonance member",
    title: "Grow a private WatchTree.",
    body: "Paste a YouTube URL to add a video you watched, or start with synthetic data.",
    urlInput: "Paste YouTube URL",
    urlPlaceholder: "https://www.youtube.com/watch?v=... or https://youtu.be/...",
    urlLookup: "Find video",
    urlAdding: "Adding...",
    urlAdded: "Added to your WatchTree",
    demo: "Use private demo history",
    import: "Advanced batch import",
    importDetails: "Google Takeout HTML/JSON",
    fileHint: "Supported: watch-history.json, watch-history.html, watch-history.htm. Archives are rejected.",
    matchingOff: "Matching is off by default",
    enableMatching: "Enable private synthetic matching",
    disableImport: "Disable matching for this import",
    confirm: "I watched this video",
    cancel: "Cancel",
    preview: "Video preview",
    accepted: "accepted",
    excluded: "excluded",
    rejected: "rejected",
    tree: "Your WatchTree",
    events: "Review private events",
    excludeEvent: "Exclude item",
    excludeCreator: "Exclude creator",
    dateFrom: "Exclude from date",
    dateTo: "through",
    applyDate: "Exclude date range",
    candidates: "Synthetic shared paths",
    synthetic: "Synthetic viewer · competition demo",
    exact: "Exact overlap",
    rare: "Rare signal",
    path: "Shared path",
    difference: "Meaningful difference",
    reveal: "Consent to reveal selected evidence",
    withdraw: "Withdraw consent",
    mutual: "Simulate mutual resonance",
    simulated: "Simulated mutual resonance · no real person",
    deleteImport: "Delete import and derived data",
    deleteAll: "Delete all WatchTree data",
    logout: "Sign out",
    empty: "No private WatchTree data yet.",
    rawLocal: "The selected raw file was parsed in a dedicated browser Worker and was not uploaded or retained.",
    insufficientSignal: "Not enough viewing history for matching yet. Add more videos.",
    rewatch: "I watched this again",
  },
  errors: {
    auth: "Sign in to continue.",
    unsupported: "Choose the extracted watch-history HTML or JSON file.",
    parse: "The file could not be parsed safely.",
    unavailable: "This resource is unavailable.",
    urlInvalid: "Enter a valid YouTube URL.",
    videoUnavailable: "This video is unavailable or private.",
    lookupFailed: "Could not retrieve video information.",
  },
};

const ko = {
  nav: { story: "이야기", privacy: "개인정보", enter: "WatchTree 시작" },
  landing: {
    eyebrow: "공명 · WatchTree",
    title: "당신이 지나온 영상의 장면들이, 같은 길을 지나온 사람을 찾습니다.",
    body: "사적인 시청 경로가 살아 있는 나무가 됩니다. 프로필·궁합 점수·심리 낙인 없이 공유된 잎의 이유를 보여줍니다.",
    primary: "비공개 데모 기록 사용",
    secondary: "개인정보 처리 보기",
    privacy: "원본 내보내기 파일은 브라우저 밖으로 나가지 않으며 매칭은 기본적으로 꺼져 있습니다.",
    privacyOverview: {
      eyebrow: "개인정보 보호 원칙",
      title: "시청 경로의 주인은 당신입니다.",
      body: "WatchTree는 직접 선택한 시청 자료만 사용하며 비교와 공개 전에 경계를 분명히 보여줍니다.",
      points: [
        "직접 추가한 YouTube URL 또는 명시적으로 선택한 파일만 사용합니다.",
        "후보는 synthetic 자료만 사용합니다.",
        "실제 사용자에게 연락하지 않습니다.",
        "명시적 동의 후에만 evidence를 공개합니다.",
        "원할 때 데이터를 삭제할 수 있습니다.",
        "YouTube 계정에 자동으로 접근하지 않습니다.",
      ],
    },
    scenes: [
      ["당신은 영상을 봤습니다.", "한 명의 synthetic 사용자가 추상적인 미디어 장면을 지나갑니다."],
      ["어떤 장면은 남았습니다.", "남은 빛 조각이 사적인 시청 경로가 됩니다."],
      ["경로를 선택합니다.", "synthetic 데모 또는 추출한 HTML/JSON 기록을 선택합니다."],
      ["WatchTree가 자랍니다.", "재시청·creator·시간·경로가 뿌리와 가지와 잎이 됩니다."],
      ["다른 나무가 나타납니다.", "server-defined synthetic 사용자가 인접한 미디어 경로를 따릅니다."],
      ["공유된 잎이 빛납니다.", "정확한 중복·희귀 신호·공유 경로·의미 있는 차이를 설명합니다."],
      ["제품으로 들어갑니다.", "제외 항목을 검토하고 하나의 증거에 동의한 뒤 명확히 표시된 simulated mutual 상태를 실행합니다."],
    ],
  },
  experience: {
    member: "공명 사용자",
    title: "사적인 WatchTree를 키워보세요.",
    body: "YouTube URL을 붙여넣어 본 영상을 추가하거나 synthetic 데이터로 시작하세요.",
    urlInput: "YouTube URL 붙여넣기",
    urlPlaceholder: "https://www.youtube.com/watch?v=... 또는 https://youtu.be/...",
    urlLookup: "영상 찾기",
    urlAdding: "추가 중...",
    urlAdded: "WatchTree에 추가됨",
    demo: "비공개 데모 기록 사용",
    import: "고급 일괄 가져오기",
    importDetails: "Google Takeout HTML/JSON",
    fileHint: "지원: watch-history.json, watch-history.html, watch-history.htm. 압축파일은 거부됩니다.",
    matchingOff: "매칭은 기본적으로 꺼져 있습니다",
    enableMatching: "비공개 synthetic 매칭 활성화",
    disableImport: "이 import의 매칭 비활성화",
    confirm: "이 영상을 봤어요",
    cancel: "취소",
    preview: "영상 미리보기",
    accepted: "수락",
    excluded: "제외",
    rejected: "거부",
    tree: "나의 WatchTree",
    events: "사적인 이벤트 검토",
    excludeEvent: "항목 제외",
    excludeCreator: "creator 제외",
    dateFrom: "날짜 제외 시작",
    dateTo: "종료",
    applyDate: "날짜 범위 제외",
    candidates: "Synthetic 공유 경로",
    synthetic: "Synthetic 사용자 · 대회 데모",
    exact: "정확한 중복",
    rare: "희귀 신호",
    path: "공유 경로",
    difference: "의미 있는 차이",
    reveal: "선택한 증거 공개에 동의",
    withdraw: "동의 철회",
    mutual: "상호 공명 시뮬레이션",
    simulated: "시뮬레이션된 상호 공명 · 실제 사용자가 아님",
    deleteImport: "import와 파생 데이터 삭제",
    deleteAll: "WatchTree 전체 데이터 삭제",
    logout: "로그아웃",
    empty: "아직 사적인 WatchTree 데이터가 없습니다.",
    rawLocal: "선택한 원본 파일은 전용 브라우저 Worker에서 파싱됐으며 업로드되거나 보존되지 않았습니다.",
    insufficientSignal: "매칭을 위한 시청 기록이 부족합니다. 영상을 더 추가해보세요.",
    rewatch: "다시 봤어요",
  },
  errors: {
    auth: "계속하려면 로그인하세요.",
    unsupported: "추출한 watch-history HTML 또는 JSON 파일을 선택하세요.",
    parse: "파일을 안전하게 파싱할 수 없습니다.",
    unavailable: "이 리소스를 사용할 수 없습니다.",
    urlInvalid: "올바른 YouTube URL을 입력하세요.",
    videoUnavailable: "이 영상은 비공개이거나 사용할 수 없습니다.",
    lookupFailed: "영상 정보를 가져올 수 없습니다.",
  },
};

export function getWatchTreeCopy(language) {
  return language === "ko" ? ko : en;
}
